### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by appengine8848** [ChiChou/bagbak#36] opened 2020-03-21 11:49 UTC
C:\Users\jk>bagbak  Chrome
FATAL ERROR
[Error: Unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')]

win10
ipad mini5+ ios12.2 uncover3.7

**Comment by ChiChou** [comment] 2020-03-21 13:01
What about manually launching the app first then retry the same command?

**Comment by appengine8848** [comment] 2020-03-21 16:20
same as old.
![_S_F7EDZ@SLMO XP)9E%MP1](https://user-images.githubusercontent.com/2500652/77230926-c889ce00-6bd2-11ea-8dd1-b02ecffdc861.png)

bagbak Chrome

**Comment by ChiChou** [comment] 2020-04-01 06:12
这个错误是 unc0ver 上 frida 不能注入 pkd，但我没有设备复现

如果你不需要 AppExtension，可以暂时升级 `bagbak@1.4.3` 并使用 `--no-extension` 跳过这个步骤
https://github.com/ChiChou/bagbak/commit/c97ad26c64e42f9e56abcf8a30b5cdc7d1e68325

**Comment by ChiChou** [comment] 2020-04-01 06:14
Duplicate of #34

**Closed by ChiChou** 2020-04-01 06:14 UTC
