### ISSUE TITLE
Dopamine is not supported

### ISSUE THREAD

**Issue by huyongnd** [ChiChou/bagbak#106] opened 2023-06-15 18:51 UTC
**Describe the bug**
砸壳过程正常，但是生成的 ipa 仍然处于加密状态

**To Reproduce**
Steps to reproduce the behavior:使用`bagcak 金铲铲之战`命令进行砸壳，期间一切正常

**Screenshots**
<img width="979" alt="image" src="https://github.com/ChiChou/bagbak/assets/112535394/5c8f9838-e725-48cf-84a9-838ff9736b3a">
<img width="993" alt="image" src="https://github.com/ChiChou/bagbak/assets/112535394/e6a8ea48-b33e-48a5-b931-5dbffe2d17b4">

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - nodejs: v19.7.0
 - frida-node: [e.g. v12.9.6]
 - frida on device version: 16.0.19
 - iOS and jailbreak version: 15.0.1
 - The app you are trying to work on [e.g. com.example.app]: 金铲铲之战（com.tencent.jkchess）

**Additional context**

**Comment by huyongnd** [comment] 2023-06-15 19:08
再来补充下，又刷了一遍你公众号文章，把 node 切成了 lts 版本重新又来了一遍还是这样，手机是 iPhone 13 mini

**Comment by ChiChou** [comment] 2023-06-15 21:49
我手上没有 Dopamine 的环境测试，checkra1n 系没有问题。

你这截图截到的信息没有关键的部分，没法判断发生了什么

**Comment by ChiChou** [comment] 2023-06-15 22:35
`DEBUG=1 bagbak --raw 金铲铲之战`

然后把输出的日志贴一下

**Comment by ChiChou** [comment] 2023-06-15 23:52
`npm i -g bagbak@latest` 升级最新（当前 3.0.8）试试，如果还不行烦请带 DEBUG 参数然后把日志发上来

`DEBUG=1 bagbak 金铲铲之战 --raw -f`

**Comment by huyongnd** [comment] 2023-06-16 14:52
感谢回复。升级了最新 3.0.9，现在不管是带不带 DEBUG现在都报错，报错内容相同：
```
chmod: changing permissions of '/private/var/containers/Bundle/Application/BF34B336-8101-4876-A9B4-B4832B1ECA5E/WeChat.app/WeChat': Operation not permitted
file:///opt/homebrew/lib/node_modules/bagbak/index.js:82
            reject(new Error(`remote command "${cmd}" exited with code ${code}`));
                   ^

Error: remote command "chmod +xX '/private/var/containers/Bundle/Application/BF34B336-8101-4876-A9B4-B4832B1ECA5E/WeChat.app/WeChat'" exited with code 1
    at Channel.<anonymous> (file:///opt/homebrew/lib/node_modules/bagbak/index.js:82:20)
    at Channel.emit (node:events:524:35)
    at doClose (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/utils.js:101:21)
    at onCHANNEL_CLOSE (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/utils.js:108:7)
    at CHANNEL_CLOSE (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:705:11)
    at 97 (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/handlers.misc.js:999:16)
    at Protocol.onPayload (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
    at ChaChaPolyDecipherBinding.decrypt (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/crypto.js:851:26)
    at Protocol.parsePacket [as _parse] (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/opt/homebrew/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:306:16)

Node.js v19.7.0
```
不带 debug：

**Comment by ChiChou** [comment] 2023-06-16 15:06
这是为了解决 #105 加入的处理。

根据[这个帖子](https://www.reddit.com/r/jailbreak/comments/13rxm9t/question_broken_permissions_in/)（[网页快照](https://webcache.googleusercontent.com/search?q=cache:a_hIM37Tl5cJ:https://www.reddit.com/r/jailbreak/comments/13rxm9t/question_broken_permissions_in/&cd=10&hl=zh-CN&ct=clnk&gl=it)）的说法，Dopamine 下运行 chmod 修改应用权限会失败。

可以编辑 `/opt/homebrew/lib/node_modules/bagbak/index.js` 暂时先把 134 行注释掉。

`await this.#executableWorkaround(mainExecutable);`

关于 ssh，这个工具的 ssh 协议不依赖系统命令，直接在 js 里实现的。能走到这一行代码说明已经连上去了

**Comment by huyongnd** [comment] 2023-06-16 15:14
没想到这么快收到回复，注释后报错：
```
main executable => /private/var/containers/Bundle/Application/BF34B336-8101-4876-A9B4-B4832B1ECA5E/WeChat.app/WeChat
pid => 3951
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Unable to find process with pid 3951]

Node.js v19.7.0
```

**Comment by ChiChou** [comment] 2023-06-16 15:36
放弃吧，证明这个版本上的 frida 不完全支持 spawn

**Comment by huyongnd** [comment] 2023-06-16 15:49
好的 谢谢啦~

**Comment by asdfzxcvbn** [comment] 2023-06-16 19:07
i can reproduce this issue on macos mojave. iphone 7 with rootful palera1n on ios 14.8:

<img width="477" alt="image" src="https://github.com/ChiChou/bagbak/assets/109937991/5aada92d-eb98-4019-ac61-49a1a18bd1cb">

this issue does not exist on any version before v3.

**Comment by ChiChou** [comment] 2023-06-16 19:38
@asdfzxcvbn it’s a bug on 3.0.x-3.0.7, please check if it still reproduces on 3.0.9

**Comment by asdfzxcvbn** [comment] 2023-06-16 19:38
> @asdfzxcvbn it’s a bug on 3.0.x-3.0.7, please check if it still reproduces on 3.0.9

my screenshot shows the bug happening on v3.0.9.

**Comment by ChiChou** [comment] 2023-06-16 19:45
@asdfzxcvbn do you have debug logs?

**Comment by asdfzxcvbn** [comment] 2023-06-16 19:56
> @asdfzxcvbn do you have debug logs?

yeah, here: https://f.zxcvbn.fyi/bagbak-debug.txt

**Comment by ChiChou** [comment] 2023-06-16 20:05
> > @asdfzxcvbn do you have debug logs?
> 
> yeah, here: https://f.zxcvbn.fyi/bagbak-debug.txt

Thanks. I am on my phone now, will get back to you later

**Comment by ChiChou** [comment] 2023-06-16 22:28
@asdfzxcvbn it should be fixed in v3.0.11
https://github.com/ChiChou/bagbak/commit/d7121f04ae00243d66ed3cad0e26b49eea01276e#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109

**Comment by asdfzxcvbn** [comment] 2023-06-16 23:11
> @asdfzxcvbn it should be fixed in v3.0.11 [d7121f0#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109](https://github.com/ChiChou/bagbak/commit/d7121f04ae00243d66ed3cad0e26b49eea01276e#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109)

otool reports back that it's decrypted like it should be, but the apps themselves crash on launch

**Comment by ChiChou** [comment] 2023-06-17 11:21
> > @asdfzxcvbn it should be fixed in v3.0.11 [d7121f0#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109](https://github.com/ChiChou/bagbak/commit/d7121f04ae00243d66ed3cad0e26b49eea01276e#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109)
> 
> otool reports back that it's decrypted like it should be, but the apps themselves crash on launch

Some times app have self protection against running when repacked. Please add `get-task-allow` to the app and debug what caused the termination, or at least give me some `idevicecrashreport` logs.

**Comment by Geczy** [comment] 2023-06-17 17:58
```
➜  ipastuff git:(main) ideviceinstaller -i ./decrypted/com.sanfordguide.amt-6.3.1.ipa 
WARNING: could not locate iTunesMetadata.plist in archive!
Copying './decrypted/com.sanfordguide.amt-6.3.1.ipa' to device... AFC Write error: 30
Error: wrote only 0 of 1048576
```

here's one thing i could find from logs. maybe this plist missing is the cause?

**Comment by asdfzxcvbn** [comment] 2023-06-17 17:59
> ```
> ➜  ipastuff git:(main) ideviceinstaller -i ./decrypted/com.sanfordguide.amt-6.3.1.ipa 
> WARNING: could not locate iTunesMetadata.plist in archive!
> Copying './decrypted/com.sanfordguide.amt-6.3.1.ipa' to device... AFC Write error: 30
> Error: wrote only 0 of 1048576
> ```
> 
> here's one thing i could find from logs. maybe this plist missing is the cause?

no, a lot of apps dont have `iTunesMetadata.plist`.

**Comment by Geczy** [comment] 2023-06-17 18:00
oh okay, well the AFC write error looks related then. the metadata plist is just a warning

**Comment by asdfzxcvbn** [comment] 2023-06-17 18:03
> > > @asdfzxcvbn it should be fixed in v3.0.11 [d7121f0#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109](https://github.com/ChiChou/bagbak/commit/d7121f04ae00243d66ed3cad0e26b49eea01276e#diff-8ca1d3a7e38fa539bf8a44bd7806039caab17e6e0861bf11a1340f325cf48103L109)
> > 
> > 
> > otool reports back that it's decrypted like it should be, but the apps themselves crash on launch
> 
> Some times app have self protection against running when repacked. Please add `get-task-allow` to the app and debug what caused the termination, or at least give me some `idevicecrashreport` logs.

spotify doesnt have sideload detection, and the dumped app works on bagbak v2.6.6. here's the crash log though: https://f.zxcvbn.fyi/Spotify-2023-06-17-140206.ips.txt

**Comment by Geczy** [comment] 2023-06-17 18:12
here's another error, i guess its a better one

```sh
➜  ipastuff git:(main) ✗ bash ./download-ipa.sh https://apps.apple.com/in/app/sanford-guide/id863196620
⬇️ Installing com.sanfordguide.amt to the phone...
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008001: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6AswP9/extracted/Payload/sanfordguideiapamt.app : 0xe8008001 (An unknown error has occurred.)
❌ Failed to install com.sanfordguide.amt. Exiting.
```

**Comment by asdfzxcvbn** [comment] 2023-06-17 18:30
> here's another error, i guess its a better one
> 
> ```shell
> ➜  ipastuff git:(main) ✗ bash ./download-ipa.sh https://apps.apple.com/in/app/sanford-guide/id863196620
> ⬇️ Installing com.sanfordguide.amt to the phone...
> ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008001: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6AswP9/extracted/Payload/sanfordguideiapamt.app : 0xe8008001 (An unknown error has occurred.)
> ❌ Failed to install com.sanfordguide.amt. Exiting.
> ```

i dont think that has anything to do with bagbak. you need to codesign your app before installing it.

**Comment by Geczy** [comment] 2023-06-17 18:30
oh yeah 😂 i forgot

**Comment by ChiChou** [comment] 2023-06-17 20:30
@asdfzxcvbn Confirmed. v3.0.0-3.0.13 hade a very critical mistake

https://github.com/ChiChou/bagbak/commit/1f4aba1962bb80d8499c09af553985c3b4833701#diff-3782ce3815652539832b31d11e68943cc074f23a3cd8527ac9159be5008afaea

**Comment by asdfzxcvbn** [comment] 2023-06-17 22:41
> @asdfzxcvbn Confirmed. v3.0.0-3.0.13 have a critical bug
> 
> [1f4aba1#diff-3782ce3815652539832b31d11e68943cc074f23a3cd8527ac9159be5008afaea](https://github.com/ChiChou/bagbak/commit/1f4aba1962bb80d8499c09af553985c3b4833701#diff-3782ce3815652539832b31d11e68943cc074f23a3cd8527ac9159be5008afaea)

finally working as intended! THANK YOU !!

**Comment by Geczy** [comment] 2023-06-17 23:09
> ```
> ➜  ipastuff git:(main) ideviceinstaller -i ./decrypted/com.sanfordguide.amt-6.3.1.ipa 
> WARNING: could not locate iTunesMetadata.plist in archive!
> Copying './decrypted/com.sanfordguide.amt-6.3.1.ipa' to device... AFC Write error: 30
> Error: wrote only 0 of 1048576
> ```
> 
> here's one thing i could find from logs. maybe this plist missing is the cause?

is this the log that helped figure out the problem?

**Comment by ChiChou** [comment] 2023-06-17 23:23
> > ```
> > ➜  ipastuff git:(main) ideviceinstaller -i ./decrypted/com.sanfordguide.amt-6.3.1.ipa 
> > WARNING: could not locate iTunesMetadata.plist in archive!
> > Copying './decrypted/com.sanfordguide.amt-6.3.1.ipa' to device... AFC Write error: 30
> > Error: wrote only 0 of 1048576
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > here's one thing i could find from logs. maybe this plist missing is the cause?
> 
> 
> is this the log that helped figure out the problem?

It shouldn’t have anything to do with afc

**Comment by ChiChou** [comment] 2023-06-17 23:24
He mentioned that v2.6.6 works so I just binary diff-ed two artifacts

**Comment by Prisoner-One** [comment] 2023-06-24 04:43
@ChiChou 感谢大佬及时修复win11打包报错的问题，因为对github不是很熟悉，所以不懂怎么规范使用issue ，就借这个老哥的地方用用。

我的win11系统，最新版的bagbak 砸壳PlugIns里的appex还是报错

C:\Users\nanshan>bagbak com.liguangming.Shadowrocket
[info] pulling app bundle from device, please be patient
[info] downloaded 1759 files and 76 folders
[info] app bundle downloaded
chmod: cannot access '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Intents.appex\Intents': No such file or directory
failed to execute "chmod +xX '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Intents.appex\Intents'", exited with code 1                                                              Failed to spawn executable at /private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Intents.appex\Intents, skipping...                                                                       Warning: Unable to dump PlugIns\Intents.appex\Intents
chmod: cannot access '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\PacketTunnel.appex\PacketTunnel': No such file or directory
failed to execute "chmod +xX '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\PacketTunnel.appex\PacketTunnel'", exited with code 1
Failed to spawn executable at /private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\PacketTunnel.appex\PacketTunnel, skipping...
Warning: Unable to dump PlugIns\PacketTunnel.appex\PacketTunnel
chmod: cannot access '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\ShareExtension.appex\ShareExtension': No such file or directory
failed to execute "chmod +xX '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\ShareExtension.appex\ShareExtension'", exited with code 1
Failed to spawn executable at /private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\ShareExtension.appex\ShareExtension, skipping...
Warning: Unable to dump PlugIns\ShareExtension.appex\ShareExtension
chmod: cannot access '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Today.appex\Today': No such file or directory
failed to execute "chmod +xX '/private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Today.appex\Today'", exited with code 1
Failed to spawn executable at /private/var/containers/Bundle/Application/C0F371B4-22E1-496F-A5DE-11B0BCFBAB4C/Shadowrocket.app/PlugIns\Today.appex\Today, skipping...
Warning: Unable to dump PlugIns\Today.appex\Today
[decrypt] Shadowrocket
Saved to com.liguangming.Shadowrocket-2.2.32.ipa

**Comment by matnledsmsadkdad** [comment] 2023-12-12 07:45
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by ChiChou** [comment] 2024-01-03 01:52
@huyongnd 3.2.0 更改了 spawn 的实现，但手上没有设备，我无法确认是否可以支持 Dopamine

**Comment by CodeTips** [comment] 2024-01-08 15:24
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Process with pid 91283 either refused to load frida-agent, or terminated during injection]

**Comment by ChiChou** [comment] 2024-01-08 16:29
> refused

frida 附加进程的时候崩了，这个得看 `Console.app` 或者 `idevicesyslog` 才能知道是谁

**Comment by ChiChou** [comment] 2024-01-08 16:30
> 系统版本 15.4.1 Dopamine 越狱 报错 node:internal/process/promises:289 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> [Error: Process with pid 91283 either refused to load frida-agent, or terminated during injection]

> refused

@CodeTips 

frida 附加进程的时候崩了，这个得看 `Console.app` 或者 `idevicesyslog` 才能知道是谁

**Comment by CodeTips** [comment] 2024-01-09 01:44
![WeChatbfaa6811475c35cc217dcf3719982c80](https://github.com/ChiChou/bagbak/assets/36583116/f0ff1654-b622-405d-be5e-3d2872fc5f80)
之前也是砸壳过程正常，生成的 ipa 仍然处于加密状态
升级到最新版就开始报错

**Comment by ChiChou** [comment] 2024-01-09 21:26
> ![WeChatbfaa6811475c35cc217dcf3719982c80](https://private-user-images.githubusercontent.com/36583116/295077625-f0ff1654-b622-405d-be5e-3d2872fc5f80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzU4NDAsIm5iZiI6MTcwNDgzNTU0MCwicGF0aCI6Ii8zNjU4MzExNi8yOTUwNzc2MjUtZjBmZjE2NTQtYjYyMi00MDVkLWJlNWUtM2QyODcyZmM1ZjgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIxMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NWQ3MDIzNmI0NDc4ZTI1YTQ0NDhmNGExODQxNDVkNTBmZjA3YzM4NmM3NzhmMzQ3YzA3OWQxYzQ2MmU0MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0cFc4tEy25vvULh0gHcFh-yJVIg77XOyk09ebApM04I) 之前也是砸壳过程正常，生成的 ipa 仍然处于加密状态 升级到最新版就开始报错

找 ReportCrash 进程的日志，而且 idevicecrashreport 工具（或者 Xcode）可以导出完整的 ips 报告

**Comment by CodeTips** [comment] 2024-01-10 13:29
[keybagd-2024-01-10-212538.ips.txt](https://github.com/ChiChou/bagbak/files/13888287/keybagd-2024-01-10-212538.ips.txt)

**Comment by ChiChou** [comment] 2024-01-10 14:26
> [keybagd-2024-01-10-212538.ips.txt](https://github.com/ChiChou/bagbak/files/13888287/keybagd-2024-01-10-212538.ips.txt) 运行完就生成了这个ips

感谢。我推送了另一个分支 https://github.com/ChiChou/bagbak/tree/dopamine

```
git clone https://github.com/ChiChou/bagbak.git
pushd bagbak
git checkout dopamine
npm i
./bin/bagbak.js --raw com.google.chrome.ios
```

试试看呢

**Comment by ChiChou** [comment] 2024-01-10 14:27
> [keybagd-2024-01-10-212538.ips.txt](https://github.com/ChiChou/bagbak/files/13888287/keybagd-2024-01-10-212538.ips.txt) 运行完就生成了这个ips

> [keybagd-2024-01-10-212538.ips.txt](https://github.com/ChiChou/bagbak/files/13888287/keybagd-2024-01-10-212538.ips.txt) 运行完就生成了这个ips

感谢 @CodeTips。我推送了另一个分支 https://github.com/ChiChou/bagbak/tree/dopamine

```
git clone https://github.com/ChiChou/bagbak.git
pushd bagbak
git checkout dopamine
npm i
./bin/bagbak.js --raw com.google.chrome.ios
```

试试看呢

**Comment by ChiChou** [comment] 2024-01-10 18:27
> info] pulling app bundle from device, please be patient [info] downloaded 3257 files and 2626 folders [info] app bundle downloaded Failed to attach to pid 11047, skipping... Warning: Unable to dump Chrome Frameworks/ChromeInternal.framework/ChromeInternal Frameworks/ChromeSSOInternal.framework/ChromeSSOInternal Failed to attach to pid 11048, skipping... Warning: Unable to dump PlugIns/content_widget_extension.appex/content_widget_extension Failed to attach to pid 11049, skipping... Warning: Unable to dump PlugIns/credential_provider_extension.appex/credential_provider_extension Failed to attach to pid 11050, skipping... Warning: Unable to dump PlugIns/intents_extension.appex/intents_extension Failed to attach to pid 11051, skipping... Warning: Unable to dump PlugIns/open_extension.appex/open_extension Failed to attach to pid 11052, skipping... Warning: Unable to dump PlugIns/search_widget_extension.appex/search_widget_extension Failed to attach to pid 11053, skipping... Warning: Unable to dump PlugIns/share_extension.appex/share_extension Failed to attach to pid 11054, skipping... Warning: Unable to dump PlugIns/widget_kit_extension.appex/widget_kit_extension file:///Users/x/Documents/Github/bagbak/index.js:233 await this.#device.kill(SpringBoard); ^
> 
> ReferenceError: SpringBoard is not defined at BagBak.dump (file:///Users/x/Documents/Github/bagbak/index.js:233:29) at async main (file:///Users/x/Documents/Github/bagbak/bin/bagbak.js:143:7)
> 
> Node.js v21.5.0 这次就只有Chrome相关的ips

说明从 launchd `posix_spawn` 也不行，只能走 `_launch_job_routine`，是个参数很复杂的私有函数。我还是想看看 ips 提示什么。另外 Console.app 里面有没有 kernel 进程类似这样的日志？

> hook..execve() killing <unsigned>[pid= 11047, uid=0]: only launchd is allowed to spawn untrusted binaries

**Comment by CodeTips** [comment] 2024-01-11 01:20
![WeChata5020341f5ef1145e440cd8771c49555](https://github.com/ChiChou/bagbak/assets/36583116/3744ab8d-6f7d-407f-9b52-3e4ed26e50e6)
hook..execve()相关的就只有这个日志
[Chrome-2024-01-11-091037.000.ips.txt](https://github.com/ChiChou/bagbak/files/13896069/Chrome-2024-01-11-091037.000.ips.txt)
上面是生成的ips,每个extension 都有, 我看内容基本一样

**Comment by ChiChou** [comment] 2024-03-02 12:07
> I think that this issue could be closed because Dopamine 2.0.9 [solves](https://github.com/opa334/Dopamine/commit/dd0bbc567e952e96197e83ec1cc796288ca8ec42) the long standing issue about Frida spawn.

@huyongnd 听说新版 Dopamine 有修复这个问题

**Comment by miticollo** [comment] 2024-03-02 13:14
@ChiChou I think I wrote too early!

**Describe the bug**
1. The app is not decrypted.
2. After decryption the app on jailbroken device can't launch anymore. Because (from `Console.app`) SpringBoard claims:
    ```text
    [com.spotify.client - signature state: Unknown, reason: Error - 49165: reason: An unexpected error was encountered (0xC00D)
    ```

**To Reproduce**
```shell
$ export SSH_USERNAME='mobile'                 
$ export SSH_PASSWORD='alpine'
$ export SSH_PORT=22          
$ export DEBUG_SCP=1
$ npx -- bagbak -U -d 'com.spotify.client'
```
[Full output](https://pastebin.com/raw/SSTC1WEg)

**Video**
https://we.tl/t-02SuRiT4FL

**Desktop:**
 - OS: macOS 13.6.4 (22G513)
 - nodejs: v21.6.2
 - frida on device version: 16.2.1
 - iOS and jailbreak version: 15.6 (19G69) and Dopamine 2.0.9
 - The app you are trying to work on `com.spotify.client`, [AppStore link](https://apps.apple.com/it/app/spotify-musica-e-podcast/id324684580)
 - `bagbak` version: 3.2.2 (commit `9ddf8b9` from `origin/main`)

**Comment by ChiChou** [comment] 2024-03-02 13:58
@miticollo I am implementing another workaround totaly ignoring `posix_spawn` right now

**Closed** 2024-03-03 00:44 UTC
